# Generated by Django 4.2.7 on 2023-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrackerapp', '0004_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
